name: Release application

on:
  push:
    tags:
      - "V*"
      - "v*"

jobs:
  build:
#    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build with executable and setup
        run: |
          pyinstaller --clean --icon dist/teamtactics2.ico -F teamtactics2.py
          iscc -DProjectBaseDir="." .\tt2setup.iss
      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            dist/TeamTactics2Setup.exe
